### ISSUE TITLE
BridgedReportRunner cannot add extra resource directory

### ISSUE THREAD

**Issue by oanqa** [belgattitude/soluble-jasper#2]
From this [code](https://github.com/belgattitude/soluble-jasper/blob/master/src/Runner/BridgedReportRunner.php#L129) we can assume the resource directory only from the report path itself.

I'm using jasper with structured directory where my resources is in another directory, so the runner cannot find it.

**Comment by belgattitude** [comment]
Yes the thing to remember is that the file must be readable both php and java sides. In other words tomcat should run on the same server as your php (or a shared dir). 

If it is the case and you experience problems with paths... The best thing to do is to be explicit in your report by using a parameter, i.e:  **`<![CDATA[$P{REPORT_DIR} + "/assets/images.png"]]>`**

Set a default value for this parameter. Very easy within jasper studio, but here is the xml version example:

```xml
<parameter name="REPORT_DIR" class="java.lang.String">
   <defaultValueExpression><![CDATA["./"]]></defaultValueExpression>
</parameter>
```

If you want to intialize it from PHP:

```php
$report = new Report(
     '/path/my_report.jrxml',
     new ReportParams([
            'REPORT_DIR'    => '/whatever/directory/you/want/to/set',
     ])
);
```
You can name the param as you want, but REPORT_DIR or SUBREPORT_DIR are commonly used. 

Otherwise you'll be lucky to host your resources (images,...) so they can be used from an URL. 

Let me know if it works for you.

PS: here's a snippet for a subreport I used once.

```xml
<subreport isUsingCache="true" runToBottom="true" overflowType="Stretch">
  <reportElement isPrintRepeatedValues="false" x="10" y="20" width="575" height="27" backcolor="#BDB5B5" uuid="ebc225b1-eba9-4778-87e7-786491b313bd"/>
  <dataSourceExpression><![CDATA[((net.sf.jasperreports.engine.data.JRXmlDataSource)$P{REPORT_DATA_SOURCE}).dataSource("/Order/lines")]]></dataSourceExpression>
  <subreportExpression><![CDATA[$P{REPORT_DIR} + "/rep_order_detail.jasper"]]></subreportExpression>
</subreport>
```

**Comment by oanqa** [comment]
For now we are using our "BridgedReportRunner" to support adding resources path to the jasper.

Thank you for your help.

**Comment by belgattitude** [comment]
You're welcome :)
